# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5LkVe9lOp3ZetiMbiYG6sZxbue1f-1f
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#load data

data =  pd.read_csv('/content/drive/MyDrive/Colab Notebooks/sales_data_sample.csv', encoding='ISO-8859-1')
data.head()

#cleaning data

# Drop null values dropna
data = data.dropna(how = 'all')
# Reset Index
data = data.reset_index(drop = True)

#change datatypes for columns
data['ORDERDATE'] = pd.to_datetime(data['ORDERDATE'])
data.info()
data.head()

# Calculate total spending per customer
customer_spending = data.groupby('CUSTOMERNAME')['SALES'].sum().reset_index()
customer_spending.columns = ['Customer', 'Total_Spending']

# Calculate purchase frequency per customer
customer_frequency = data.groupby('CUSTOMERNAME')['ORDERNUMBER'].nunique().reset_index()
customer_frequency.columns = ['Customer', 'Frequency']

# Merge the two dataframes
customer_data = pd.merge(customer_spending, customer_frequency, on='Customer')

# Categorize customers (example: high-value, low-value based on total spending)
customer_data['Value_Segment'] = pd.qcut(customer_data['Total_Spending'], 3, labels=['Low-Value', 'Medium-Value', 'High-Value'])

print(customer_data.head())

# Calculate monthly sales
data['Month'] = data['ORDERDATE'].dt.to_period('M')
monthly_sales = data.groupby('Month')['SALES'].sum().reset_index()
print(monthly_sales.head())

data['PRODUCTLINE'].value_counts().plot(kind = 'bar', color = '00000')
plt.title('Total product line by MSRP')
plt.xlabel('PRODUCTLINE')
plt.ylabel('MSRP')

data['ORDERDATE'].value_counts().plot(kind = 'line', color = '00000')
plt.title('Sales by Year')
plt.xlabel('ORDERDATE')
plt.ylabel(' SALES')

shipping = data['STATUS'].value_counts()

plt.pie(shipping,
        labels = shipping.index,
        autopct = '%1.1f%%',
        colors = ['lightblue','blue','coral','black']
        );

sns.distplot(data['YEAR_ID'])

data['COUNTRY'].value_counts().plot(kind = 'line', color = '00000')
plt.title('Sales by Country')
plt.xlabel('COUNTRY')
plt.ylabel(' SALES')